In [27]:
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import time
import os

In [28]:
#check dati maggio

In [29]:
path="/mnt/c/Users/isabe/OneDrive/Desktop/Lavoro/Tuscia/chiara/peaks_background/bufale_isa/"
os.chdir(path)

In [30]:
file_path_robot = './dati_bufale/dati_grezzi_agosto_luglio/Luglio/Dati_robot/Mungiture_1-31_luglio.csv'
#file_path_bufale_maggio = './dati_bufale/dati_maggio_giugno/Combined_MooLogger_Data_maggio.csv'
#file_path_bufale_giugno = './dati_bufale/dati_maggio_giugno/giugno_bufale-05302024000000-06142024235900.csv'


file_path_bufale = './dati_bufale/data_to_merge/3_Amaseno Luglio 2024-07012024115100-07312024115100.csv'

In [31]:
df_robot = pd.read_csv(file_path_robot, header=1, sep=";", usecols=["Ora inizio", "Numero animale",
                                "Azione", "Durata (mm:ss)",
                                "Produzione (kg)", "Numero mungitura"])
'''
df_robot = pd.read_excel(file_path_robot, header=1, usecols=["Ora inizio", "Numero animale",
                                "Azione", "Durata (mm:ss)",
                                "Produzione (kg)", "Numero mungitura"])
'''
df_robot['ID_animal'] = df_robot['Numero animale']
df_robot = df_robot.drop(columns = ['Numero animale'])

In [32]:
df_robot.head()

,Ora inizio,Azione,Durata (mm:ss),Produzione (kg),Numero mungitura,ID_animal
0,01/07/2024 00:13,Mungitura,05:00,"3,42",1.0,1687
1,01/07/2024 00:18,Mungitura,09:32,"1,20",1.0,5983
2,01/07/2024 00:30,Mungitura,05:13,"2,32",1.0,245572
3,01/07/2024 00:38,Rifiutata,00:00,NaN,NaN,245584
4,01/07/2024 00:38,Mungitura,07:48,"5,51",1.0,233727

In [ ]:
#test dati luglio agosto (impossibile senza dati robot)

In [ ]:
#gestire dati agosto, formato diverso

In [33]:
#file_path_bufale = "./dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Luglio/Dati_moologger/luglio_detrended.csv"

df_sniffer = pd.read_csv(file_path_bufale, usecols=['timestamp', 'CH4', 'CH4-mgm3', 'CO2', 'CO2-mgm3'], skiprows=1)
df_sniffer.head()

/tmp/ipykernel_1029/981426994.py:3: DtypeWarning: Columns (1,2,3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sniffer = pd.read_csv(file_path_bufale, usecols=['timestamp', 'CH4', 'CH4-mgm3', 'CO2', 'CO2-mgm3'], skiprows=1)

                    timestamp    CH4 CH4-mgm3    CO2  CO2-mgm3
0  07/01/2024 09:51:00.024698  195.8  128.452  645.1  1161.186
1  07/01/2024 09:51:01.026654  185.2  121.498  627.0  1128.606
2  07/01/2024 09:51:02.029196  195.8  128.452  602.3  1084.145
3  07/01/2024 09:51:03.032440  188.8   123.86  605.6  1090.085
4  07/01/2024 09:51:04.035013  191.8  125.828  611.2  1100.166

In [ ]:
#FOLLIA PER DATI MALATI GIUGNO

In [8]:
df_sniffer['timestamp'].loc[1628472]

'2024-06-02 10:56:29'

In [9]:
df_sniffer.tail()
temp = str(df_sniffer['timestamp'].loc[1628472])
temp = temp + ".00"
print(temp)
df_sniffer['timestamp'].loc[1628472] = temp





#temp = pd.to_datetime(df_sniffer['timestamp'].loc[1628472])#, format=="%Y-%m-%d %H:%M:%S")
#df_sniffer['timestamp'].loc[1628472] = temp
print(df_sniffer['timestamp'].loc[1628472])
print(df_sniffer.loc[1628472])

2024-06-02 10:56:29.00
2024-06-02 10:56:29.00
timestamp    2024-06-02 10:56:29.00
CH4                           712.2
CH4-mgm3                    467.229
CO2                           664.5
CO2-mgm3                   1196.106
Name: 1628472, dtype: object

/tmp/ipykernel_31795/3954535289.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_sniffer['timestamp'].loc[1628472] = temp

In [10]:
df_sniffer['timestamp'] = pd.to_datetime(df_sniffer['timestamp'])#, format="%Y-%m-%d %H:%M:%S.%f")
df_sniffer['date'] = [d.date() for d in df_sniffer['timestamp']]
df_sniffer['time'] = [d.time() for d in df_sniffer['timestamp']]

In [11]:
#check and clean data for wrong dates (i.e. moologger in the lab)

date_str = '2024-05-15'
start_date = datetime.strptime(date_str, '%Y-%m-%d').date()
type(start_date)
df_sniffer = df_sniffer[df_sniffer['date'] >= start_date]

In [ ]:
df_sniffer.loc[1628472]

In [ ]:
#create clean moologger data withouth interception of useless data

output_file = './dati_bufale/data_to_merge/4_Combined_MooLogger_agosto_filtered.csv'
df_sniffer.to_csv(output_file, index=False)

In [ ]:

#RICOMINCIA DA QUI

In [34]:
df_sniffer['timestamp'] = pd.to_datetime(df_sniffer['timestamp'])#, format="%Y-%m-%d %H:%M:%S.%f")
df_sniffer['date'] = [d.date() for d in df_sniffer['timestamp']]
df_sniffer['time'] = [d.time() for d in df_sniffer['timestamp']]

In [35]:
#check and clean data for wrong dates (i.e. moologger in the lab)

date_str = '2024-07-09'
start_date = datetime.strptime(date_str, '%Y-%m-%d').date()
type(start_date)
df_sniffer = df_sniffer[df_sniffer['date'] < start_date]

In [36]:
df_robot.tail()

,Ora inizio,Azione,Durata (mm:ss),Produzione (kg),Numero mungitura,ID_animal
5965,31/07/2024 22:40,Mungitura,13:49,"0,03",3.0,245581
5966,31/07/2024 22:54,Rifiutata,00:00,NaN,NaN,9076
5967,31/07/2024 23:12,Mungitura,06:53,"2,11",3.0,234554
5968,31/07/2024 23:25,Rifiutata,00:00,NaN,NaN,5968
5969,31/07/2024 23:54,Rifiutata,00:00,NaN,NaN,7854

In [37]:
df_sniffer.tail()

,timestamp,CH4,CH4-mgm3,CO2,CO2-mgm3,date,time
652941,2024-07-08 23:59:55.138931,90.6,59.437,3865.9,6958.655,2024-07-08,23:59:55.138931
652942,2024-07-08 23:59:56.142226,72.7,47.694,2702.3,4864.164,2024-07-08,23:59:56.142226
652943,2024-07-08 23:59:57.145014,59.1,38.772,1825.1,3285.196,2024-07-08,23:59:57.145014
652944,2024-07-08 23:59:58.148022,58.7,38.509,1311.3,2360.352,2024-07-08,23:59:58.148022
652945,2024-07-08 23:59:59.149962,53.7,35.229,1038.9,1870.029,2024-07-08,23:59:59.149962

In [38]:
# Filtraggio dei record con "Status" uguale a "Avvenuto con successo"
df_robot = df_robot[df_robot['Azione'] == 'Mungitura']

# Conversione e arrotondamento della colonna 'timestamp' al secondo più vicino nel DataFrame del Mologger
df_sniffer['timestamp'] = pd.to_datetime(df_sniffer['timestamp'], errors='coerce')

In [ ]:
type(df_robot['Durata (mm:ss)'][9])

In [ ]:
#PER DATI PAZZI GIUGNO - SETTEMBRE

In [15]:
df_robot['Durata (mm:ss)'] = df_robot['Durata (mm:ss)'].apply(lambda x: str(x))
df_robot['Durata (mm:ss)'] = df_robot['Durata (mm:ss)'].apply(lambda x: x.split(":"))
print(df_robot['Durata (mm:ss)'].head())

1    [00, 06, 55]
2    [00, 05, 16]
4    [00, 11, 58]
7    [00, 17, 22]
9    [00, 06, 37]
Name: Durata (mm:ss), dtype: object

In [16]:
for index, row in df_robot.iterrows():
    temp = row['Durata (mm:ss)']
    temp = temp[1] + ":" + temp[2]
    row['Durata (mm:ss)'] = temp
    df_robot.loc[index, 'Durata (mm:ss)'] = row['Durata (mm:ss)']
    #print(row['Durata (mm:ss)'])

In [17]:
df_robot.head()

,Ora inizio,Azione,Durata (mm:ss),Produzione (kg),Numero mungitura,ID_animal
1,2024-05-15 00:07:08,Mungitura,06:55,2.72,1.0,7687
2,2024-05-15 00:15:10,Mungitura,05:16,4.66,1.0,233733
4,2024-05-15 00:26:36,Mungitura,11:58,4.45,1.0,245577
7,2024-05-15 01:04:04,Mungitura,17:22,1.22,1.0,1646
9,2024-05-15 01:30:55,Mungitura,06:37,3.91,1.0,245600

In [39]:
#RICOMINCIA DA QUI

df_robot['Milking_duration'] = df_robot['Durata (mm:ss)'].apply(lambda x: str(x))
df_robot['Duration (hh:mm:ss)'] = '00:' + df_robot['Milking_duration']

df_robot['Duration (hh:mm:ss)'] = pd.to_timedelta(df_robot['Duration (hh:mm:ss)'])

In [21]:
df_robot.head()

,Ora inizio,Azione,Durata (mm:ss),Produzione (kg),Numero mungitura,ID_animal,Milking_duration,Duration (hh:mm:ss)
0,2024-07-01 00:13:00,Mungitura,05:00,"3,42",1.0,1687,05:00,0 days 00:05:00
1,2024-07-01 00:18:00,Mungitura,09:32,"1,20",1.0,5983,09:32,0 days 00:09:32
2,2024-07-01 00:30:00,Mungitura,05:13,"2,32",1.0,245572,05:13,0 days 00:05:13
4,2024-07-01 00:38:00,Mungitura,07:48,"5,51",1.0,233727,07:48,0 days 00:07:48
6,2024-07-01 00:51:00,Mungitura,12:33,"2,75",1.0,5968,12:33,0 days 00:12:33

In [20]:
df_sniffer.head()

,timestamp,CH4,CH4-mgm3,CO2,CO2-mgm3,date,time
0,2024-05-15 22:00:00.066998,1177.8,772.679,2121.7,3819.079,2024-05-15,22:00:00.066998
1,2024-05-15 22:00:00.567837,1192.0,783.569,2245.6,4042.1,2024-05-15,22:00:00.567837
2,2024-05-15 22:00:01.069377,1146.7,752.276,2609.2,4696.583,2024-05-15,22:00:01.069377
3,2024-05-15 22:00:01.570569,1173.0,769.53,3199.1,5758.409,2024-05-15,22:00:01.570569
4,2024-05-15 22:00:02.072336,1316.7,863.803,4258.9,7666.058,2024-05-15,22:00:02.072336

In [40]:
#df_robot['Ora inizio'] = df_robot['Ora inizio'].apply(lambda x: x.strptime('%Y/%m/%d %H:%M:%S'))

df_robot['Ora inizio'] = pd.to_datetime(df_robot['Ora inizio'], format='%d/%m/%Y %H:%M')

In [41]:
df_robot_sorted = df_robot.sort_values('Ora inizio')

#df_robot_sorted=df_robot
df_robot_sorted['Ora inizio'] = pd.to_datetime(df_robot_sorted['Ora inizio'])

#associazione della durata di mungitura e ingresso bufala a misurazione sniffer con taglio del dato all'uscita dell'animale
df_robot_sorted['Milking_end'] = None
df_robot_sorted['Milking_end'] = df_robot_sorted['Ora inizio'] + df_robot_sorted['Duration (hh:mm:ss)']

In [ ]:
print(df_robot.shape)
print(df_sniffer.shape)
print(df_robot_sorted.shape)

In [42]:
#####
             
# Unione dei DataFrame df_robot e df_mologger basata sulla data con tolleranza di 1 minuto
# pulisci il timestamp per valori nan o assenti
df_sniffer.dropna(subset=['timestamp'], inplace=True)
df_sniffer.dropna(subset=['CH4'], inplace=True)

merged_df = pd.merge_asof(df_sniffer, df_robot_sorted, left_on='timestamp', right_on='Ora inizio')

merged_df=merged_df[merged_df['timestamp'] < merged_df['Milking_end']]

na_count = merged_df['CH4'].value_counts().get('N.A.', 0)
print("Count of 'N.A.' in the column CH4:", na_count)

Count of 'N.A.' in the column CH4: 0

In [43]:
merged_df.tail()

,timestamp,CH4,CH4-mgm3,CO2,CO2-mgm3,date,time,Ora inizio,Azione,Durata (mm:ss),Produzione (kg),Numero mungitura,ID_animal,Milking_duration,Duration (hh:mm:ss),Milking_end
652941,2024-07-08 23:59:55.138931,90.6,59.437,3865.9,6958.655,2024-07-08,23:59:55.138931,2024-07-08 23:57:00,Mungitura,05:24,"2,27",1.0,9076,05:24,0 days 00:05:24,2024-07-09 00:02:24
652942,2024-07-08 23:59:56.142226,72.7,47.694,2702.3,4864.164,2024-07-08,23:59:56.142226,2024-07-08 23:57:00,Mungitura,05:24,"2,27",1.0,9076,05:24,0 days 00:05:24,2024-07-09 00:02:24
652943,2024-07-08 23:59:57.145014,59.1,38.772,1825.1,3285.196,2024-07-08,23:59:57.145014,2024-07-08 23:57:00,Mungitura,05:24,"2,27",1.0,9076,05:24,0 days 00:05:24,2024-07-09 00:02:24
652944,2024-07-08 23:59:58.148022,58.7,38.509,1311.3,2360.352,2024-07-08,23:59:58.148022,2024-07-08 23:57:00,Mungitura,05:24,"2,27",1.0,9076,05:24,0 days 00:05:24,2024-07-09 00:02:24
652945,2024-07-08 23:59:59.149962,53.7,35.229,1038.9,1870.029,2024-07-08,23:59:59.149962,2024-07-08 23:57:00,Mungitura,05:24,"2,27",1.0,9076,05:24,0 days 00:05:24,2024-07-09 00:02:24

In [44]:

#print("Data types of all columns:")
#print(merged_df.dtypes)

merged_df['CH4'] = pd.to_numeric(merged_df['CH4'], errors='coerce')

merged_df.replace(',', '.', regex=True, inplace=True)
merged_df.replace(':', '.', regex=True, inplace=True)
merged_df['Milking_duration'] = pd.to_numeric(merged_df['Milking_duration'], errors='coerce')
merged_df['Produzione (kg)'] = pd.to_numeric(merged_df['Produzione (kg)'], errors='coerce')

#print("Data types of all columns:")
#print(merged_df.dtypes)

#DO NOT perform if data are DETRENDED
#merged_df=merged_df[merged_df['CH4'] > 0]

#merged_df=merged_df[merged_df['CH4'] < 5000]

#output_file = './dati_bufale/merged_buffalo_sniffer_AMS.csv'
#merged_df.to_csv(output_file, index=False)

In [ ]:
print(df_sniffer.shape)
print(merged_df.head())
print(merged_df.shape)

In [45]:
###CONTA MUNGITURE PER PERIODO
# Initialize 'Milking_number' column
merged_df['Milking_number'] = 0

# Initialize variables
milking_count = 0
previous_id = None

# Iterate through the DataFrame
for index, row in merged_df.iterrows():
    current_id = row['ID_animal']
   
    if current_id != previous_id:
        milking_count += 1
   
    # Update the 'Milking_number' column
    merged_df.at[index, 'Milking_number'] = milking_count
   
    # Update previous_id for the next iteration
    previous_id = current_id
    

output_file = './dati_bufale/dati_grezzi_agosto_luglio/Luglio/protocollo_2/ch4_merged_sniffer_AMS_01-09_07_24.csv'
merged_df.to_csv(output_file, index=False)

In [ ]:
merged_df[1860:1870]

In [46]:
merged_df.tail(10)

,timestamp,CH4,CH4-mgm3,CO2,CO2-mgm3,date,time,Ora inizio,Azione,Durata (mm:ss),Produzione (kg),Numero mungitura,ID_animal,Milking_duration,Duration (hh:mm:ss),Milking_end,Milking_number
652936,2024-07-08 23:59:50.125403,55.4,36.344,1718.5,3093.315,2024-07-08,23:59:50.125403,2024-07-08 23:57:00,Mungitura,05.24,2.27,1.0,9076,5.24,0 days 00:05:24,2024-07-09 00:02:24,610
652937,2024-07-08 23:59:51.128682,54.7,35.885,1277.6,2299.691,2024-07-08,23:59:51.128682,2024-07-08 23:57:00,Mungitura,05.24,2.27,1.0,9076,5.24,0 days 00:05:24,2024-07-09 00:02:24,610
652938,2024-07-08 23:59:52.131711,82.4,54.057,1764.6,3176.296,2024-07-08,23:59:52.131711,2024-07-08 23:57:00,Mungitura,05.24,2.27,1.0,9076,5.24,0 days 00:05:24,2024-07-09 00:02:24,610
652939,2024-07-08 23:59:53.134962,138.7,91.058,3560.3,6408.572,2024-07-08,23:59:53.134962,2024-07-08 23:57:00,Mungitura,05.24,2.27,1.0,9076,5.24,0 days 00:05:24,2024-07-09 00:02:24,610
652940,2024-07-08 23:59:54.136498,103.3,67.769,4423.6,7962.52,2024-07-08,23:59:54.136498,2024-07-08 23:57:00,Mungitura,05.24,2.27,1.0,9076,5.24,0 days 00:05:24,2024-07-09 00:02:24,610
652941,2024-07-08 23:59:55.138931,90.6,59.437,3865.9,6958.655,2024-07-08,23:59:55.138931,2024-07-08 23:57:00,Mungitura,05.24,2.27,1.0,9076,5.24,0 days 00:05:24,2024-07-09 00:02:24,610
652942,2024-07-08 23:59:56.142226,72.7,47.694,2702.3,4864.164,2024-07-08,23:59:56.142226,2024-07-08 23:57:00,Mungitura,05.24,2.27,1.0,9076,5.24,0 days 00:05:24,2024-07-09 00:02:24,610
652943,2024-07-08 23:59:57.145014,59.1,38.772,1825.1,3285.196,2024-07-08,23:59:57.145014,2024-07-08 23:57:00,Mungitura,05.24,2.27,1.0,9076,5.24,0 days 00:05:24,2024-07-09 00:02:24,610
652944,2024-07-08 23:59:58.148022,58.7,38.509,1311.3,2360.352,2024-07-08,23:59:58.148022,2024-07-08 23:57:00,Mungitura,05.24,2.27,1.0,9076,5.24,0 days 00:05:24,2024-07-09 00:02:24,610
652945,2024-07-08 23:59:59.149962,53.7,35.229,1038.9,1870.029,2024-07-08,23:59:59.149962,2024-07-08 23:57:00,Mungitura,05.24,2.27,1.0,9076,5.24,0 days 00:05:24,2024-07-09 00:02:24,610