In [1]:
#QUESTO SCRIPT TOGLIE IL PRIMO MINUTO DI DATI X MUNGITURA, IPOTIZZANDO CHE LE PRIME LETTURE
#NON SI RIFERISCANO ALL ANIMALE PRESENTE MA A QUELLO PRECEDENTE. DOPODICHE FA UN ULTERIORE TAGLIO 
#ANDANDO A PRENDERE I SUCCESSIVI 240 SEC (4MIN) PER MUNGITURA

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
import os

In [2]:
path="/mnt/c/Users/isabe/OneDrive/Desktop/Lavoro/Tuscia/chiara/peaks_background/bufale_isa/"
os.chdir(path)

In [60]:
mandria_path = './dati_bufale/dati_grezzi_agosto_luglio/Luglio/protocollo_2/ch4_clean_out_neg_bg_10.csv'
mandria = pd.read_csv(mandria_path)

In [61]:
mandria['ID_animal'] = mandria['ID_animal'].apply(lambda x: int(x))
mandria['Milking_number'] = mandria['Milking_number'].apply(lambda x: int(x))

In [70]:
#dividing and plotting each milking (keeping animal information)
#inspection of milking with calculus of mean, median, standard deviation without removal of data

animals = list(set(mandria['ID_animal']))
mungiture = list(set(mandria['Milking_number']))
print(len(animals))
print(len(mungiture))

matrix= list()

mandria_cutted=mandria

36
1532

In [63]:
mandria_cutted.tail()

,timestamp,CH4,date,Ora inizio,Produzione (kg),ID_animal,Milking_duration,Milking_number
378932,2024-07-23 12:41:09.669489,37.53,2024-07-23,2024-07-23 12:38:00,3.07,233733,4.33,1740
378933,2024-07-23 12:41:10.671814,62.63,2024-07-23,2024-07-23 12:38:00,3.07,233733,4.33,1740
378934,2024-07-23 12:41:11.673571,15.73,2024-07-23,2024-07-23 12:38:00,3.07,233733,4.33,1740
378935,2024-07-23 12:41:12.675888,15.63,2024-07-23,2024-07-23 12:38:00,3.07,233733,4.33,1740
378936,2024-07-23 12:41:13.678366,19.33,2024-07-23,2024-07-23 12:38:00,3.07,233733,4.33,1740

In [71]:
mandria_cutted['Milking_duration'] = mandria_cutted['Milking_duration'].apply(lambda x: str(x))

In [68]:
print(len(set(mandria_cutted['Milking_number'])))

1532

In [72]:
# Convert 'milking_duration' to seconds
mandria_cutted['milking_duration_seconds'] = mandria_cutted['Milking_duration'].apply(lambda x: int(x.split('.')[0]) * 60 + int(x.split('.')[1]))


print(mandria_cutted.shape)
print(len(set(mandria_cutted['Milking_number'])))

# Filter the DataFrame to keep only records of milkings longer than 200 seconds
mandria_cutted = mandria_cutted[mandria_cutted['milking_duration_seconds'] > 240]

print(mandria_cutted.shape)
print(len(set(mandria_cutted['Milking_number'])))

(378937, 10)
1532
(378916, 10)
1531

In [ ]:

#Assign a progressive number of seconds starting from 1 within each milking session
mandria_cutted['progressive_seconds'] = mandria_cutted.groupby(['ID_animal', 'Milking_number']).cumcount() + 1

print(mandria_cutted.shape)
print(len(set(mandria_cutted['Milking_number'])))

In [ ]:
# Filter the DataFrame to keep only records after the first minute (60 seconds)
#mandria_cutted = mandria_cutted[mandria_cutted['progressive_seconds'] > 60]
#for i in range(0,300000):
#    if mandria_cutted[i]['milking_duration_seconds']<60:
#        print(mandria_cutted[i])

mandria_cutted = mandria_cutted[mandria_cutted['milking_duration_seconds'] > 60]

print(mandria_cutted.shape)
print(len(set(mandria_cutted['Milking_number'])))

# Filter the DataFrame to keep only records of milkings longer than 200 seconds
mandria_cutted = mandria_cutted[mandria_cutted['milking_duration_seconds'] > 240]

mandria_cutted = mandria_cutted.reset_index()
print(mandria_cutted[mandria_cutted['milking_duration_seconds'] < 240])

print(mandria_cutted.shape)
print(len(set(mandria_cutted['Milking_number'])))

In [45]:
type(mandria_cutted['milking_duration_seconds'][1])

numpy.int64

In [10]:
#taglio a 4 minuti per mungitura (240+60=300)
filtered_df2 = filtered_df[filtered_df['progressive_seconds'] <= 300]

In [ ]:
filtered_df2.shape

In [11]:
print(len(set(filtered_df2['Milking_number'])))

257

In [ ]:
ch4_mean = filtered_df2['CH4'].mean()
print(ch4_mean)

# Salva il DataFrame combinato in un nuovo file CSV.
#mandria_path = './dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Luglio/ch4_clean_out_bg_10.csv'

output_file = './dati_bufale/dati_settembre/protocollo_2/ch4_cutted_milkings.csv'
filtered_df2.to_csv(output_file, index=False)

In [53]:
ch4_cutted_milkings = './dati_bufale/dati_grezzi_agosto_luglio/Luglio/protocollo_2/ch4_cutted_milkings.csv'
ch4_cut_milkings = pd.read_csv(ch4_cutted_milkings)
ch4_cut_milkings.head()

,timestamp,CH4,date,Ora inizio,Produzione (kg),ID_animal,Milking_duration,Milking_number,milking_duration_seconds,progressive_seconds
0,2024-07-01 09:55:09.644802,386.1,2024-07-01,2024-07-01 09:54:00,1.44,5983,9.27,1,567,61
1,2024-07-01 09:55:10.647990,283.4,2024-07-01,2024-07-01 09:54:00,1.44,5983,9.27,1,567,62
2,2024-07-01 09:55:11.650945,230.1,2024-07-01,2024-07-01 09:54:00,1.44,5983,9.27,1,567,63
3,2024-07-01 09:55:12.654098,209.6,2024-07-01,2024-07-01 09:54:00,1.44,5983,9.27,1,567,64
4,2024-07-01 09:55:13.655513,188.2,2024-07-01,2024-07-01 09:54:00,1.44,5983,9.27,1,567,65

In [ ]:
ch4_cut_milkings[ch4_cut_milkings['Milking_number'] == 740]