In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
import os

In [2]:
path="/mnt/c/Users/isabe/OneDrive/Desktop/Lavoro/Tuscia/chiara/peaks_background/bufale_isa/"
os.chdir(path)

In [3]:
#Lettura file dati mergiati ch4-bufale e robot, selezionando solo colonne che ci servono per questo momento.

mandria_path = './dati_bufale/dati_settembre/protocollo_2/ch4_peaks_filtered.csv'
mandria = pd.read_csv(mandria_path, usecols = ['CH4', 'ID_animal', 'Milking_number', 'Produzione (kg)'])

mandria['ID_animal'] = mandria['ID_animal'].apply(lambda x: int(x))
mandria['Milking_number'] = mandria['Milking_number'].apply(lambda x: int(x))

animals = list(set(mandria['ID_animal']))
mungiture = list(set(mandria['Milking_number']))


print(len(animals))
print(len(mungiture))

32
166

In [4]:
mandria.tail()

         CH4  Produzione (kg)  ID_animal  Milking_number
39726  62.64             3.67     245577             257
39727  32.34             3.67     245577             257
39728  34.24             3.67     245577             257
39729  34.64             3.67     245577             257
39730  36.64             3.67     245577             257

In [ ]:
#mandria_dropped = mandria
#mandria_dropped = pd.DataFrame(mandria[['CH4', 'Milking_number']])

In [ ]:
#mandria_dropped.head()

In [5]:
# Group by 'Milking_number' and calculate the mean of 'Methane'
average_methane_per_milking = mandria.groupby('Milking_number').mean().reset_index()

average_methane_per_milking.head()

#METANO MEDIO EMESSO PER MUNGITURA
mean_ch4_per_milking = average_methane_per_milking['CH4'].mean()

In [ ]:
#mandria_animal = mandria
#mandria_animal = pd.DataFrame(mandria[['CH4', 'Milking_number', 'ID_animal']])

In [ ]:
#mandria_animal.head()

In [6]:
# Group by 'Animal_ID' and count the unique 'Milking_number'
milking_count_per_animal = mandria.groupby('ID_animal')['Milking_number'].nunique().reset_index()

# Step 2: Group by 'Animal_ID' to calculate the average and standard deviation of the means
mean_and_std = average_methane_per_milking.groupby('ID_animal').agg({
    'CH4': ['mean', 'std'],
    'Produzione (kg)': 'mean'}).reset_index()

# Flatten the MultiIndex columns resulting from the aggregation
mean_and_std.columns = ['ID_animal', 'CH4_mean', 'CH4_std', 'avg_produzione']

In [7]:

# Salva il DataFrame combinato in un nuovo file CSV.
output_file = './dati_bufale/dati_settembre/protocollo_2/mean_ch4_per_animal.xlsx'
mean_and_std.to_excel(output_file, index=False)


output_file_2 = './dati_bufale/dati_settembre/protocollo_2/mean_ch4_per_milking.xlsx'
average_methane_per_milking.to_excel(output_file_2, index=False)
print("File CSV combinato creato con successo.")

File CSV combinato creato con successo.

In [8]:
mean_and_std.head()

   ID_animal    CH4_mean     CH4_std  avg_produzione
0     1646.0  146.484688   30.234283          1.7725
1     1687.0  100.029861   27.908964          3.7150
2     2857.0  190.735521  136.449997          2.4475
3     3098.0   97.162321   38.008851          5.9900
4     4724.0  120.825417   86.237047          3.1180

In [9]:
average_methane_per_milking.tail()

     Milking_number         CH4  Produzione (kg)  ID_animal
161             250  252.794410             3.15   245582.0
162             253  206.242500             3.29     7687.0
163             254  380.117083             0.24     5968.0
164             256   58.499167             2.44   245591.0
165             257   85.679583             3.67   245577.0