In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
import os

In [2]:
path="/mnt/c/Users/isabe/OneDrive/Desktop/Lavoro/Tuscia/chiara/peaks_background/bufale_isa/"
os.chdir(path)

In [3]:
#Lettura file dati mergiati ch4-bufale e robot, selezionando solo colonne che ci servono per questo momento.

mandria_path = './dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Luglio/protocollo_1/ch4_cutted_milkings.csv'
mandria = pd.read_csv(mandria_path, usecols = ['CH4', 'ID_animal', 'Milking_number', 'Produzione (kg)'])

mandria['ID_animal'] = mandria['ID_animal'].apply(lambda x: int(x))
mandria['Milking_number'] = mandria['Milking_number'].apply(lambda x: int(x))

animals = list(set(mandria['ID_animal']))
mungiture = list(set(mandria['Milking_number']))


print(len(animals))
print(len(mungiture))

36
1740

In [4]:
mandria.tail()

               CH4  Produzione (kg)  ID_animal  Milking_number
520510  126.456320             3.07     233733            1740
520511  101.456450             3.07     233733            1740
520512   78.356581             3.07     233733            1740
520513   59.856711             3.07     233733            1740
520514    2.666536             3.73     245591            1741

In [ ]:
#mandria_dropped = mandria
#mandria_dropped = pd.DataFrame(mandria[['CH4', 'Milking_number']])

In [ ]:
#mandria_dropped.head()

In [5]:
# Group by 'Milking_number' and calculate the mean of 'Methane'
average_methane_per_milking = mandria.groupby('Milking_number').mean().reset_index()

average_methane_per_milking.head()

#METANO MEDIO EMESSO PER MUNGITURA
mean_ch4_per_milking = average_methane_per_milking['CH4'].mean()

In [ ]:
#mandria_animal = mandria
#mandria_animal = pd.DataFrame(mandria[['CH4', 'Milking_number', 'ID_animal']])

In [ ]:
#mandria_animal.head()

In [6]:
# Group by 'Animal_ID' and count the unique 'Milking_number'
milking_count_per_animal = mandria.groupby('ID_animal')['Milking_number'].nunique().reset_index()

# Step 2: Group by 'Animal_ID' to calculate the average and standard deviation of the means
mean_and_std = average_methane_per_milking.groupby('ID_animal').agg({
    'CH4': ['mean', 'std'],
    'Produzione (kg)': 'mean'}).reset_index()

# Flatten the MultiIndex columns resulting from the aggregation
mean_and_std.columns = ['ID_animal', 'CH4_mean', 'CH4_std', 'avg_produzione']

In [7]:

# Salva il DataFrame combinato in un nuovo file CSV.
output_file = './dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Luglio/protocollo_1/mean_ch4_per_animal.xlsx'
mean_and_std.to_excel(output_file, index=False)


output_file_2 = './dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Luglio/protocollo_1/mean_ch4_per_milking.xlsx'
average_methane_per_milking.to_excel(output_file_2, index=False)
print("File CSV combinato creato con successo.")

File CSV combinato creato con successo.

In [8]:
mean_and_std.head()

   ID_animal    CH4_mean    CH4_std  avg_produzione
0     1007.0  133.603017  76.016043        1.651875
1     1646.0  129.604413  83.773599        1.974419
2     1687.0  105.435277  72.820287        4.145455
3     2857.0  128.154974  70.154528        2.016154
4     3098.0  133.990775  75.966365        6.610000

In [9]:
average_methane_per_milking.tail()

      Milking_number        CH4  Produzione (kg)  ID_animal
1735            1737  25.912153             4.71   245584.0
1736            1738   9.162061             3.68   245582.0
1737            1739  45.808157             2.94   233735.0
1738            1740  61.535324             3.07   233733.0
1739            1741   2.666536             3.73   245591.0