In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import time
import os

In [ ]:
#check dati maggio

In [2]:
path="/mnt/c/Users/isabe/OneDrive/Desktop/Lavoro/Tuscia/chiara/peaks_background/bufale_isa/"
os.chdir(path)

In [15]:
file_path_robot = './dati_bufale/vecchi-maggio/Mungiture_gruppo_14gg_mag.csv'
file_path_bufale_maggio = './dati_bufale/dati_maggio_giugno/Combined_MooLogger_Data_maggio.csv'
file_path_bufale_giugno = './dati_bufale/dati_maggio_giugno/giugno_bufale-05302024000000-06142024235900.csv'

In [11]:
df_robot = pd.read_csv(file_path_robot, header=1, sep=";", usecols=["Ora inizio", "Numero animale",
                                "Azione", "Durata (mm:ss)",
                                "Produzione (kg)", "Numero mungitura"])
df_robot['ID_animal'] = df_robot['Numero animale']
df_robot = df_robot.drop(columns = ['Numero animale'])

In [16]:
df_sniffer_maggio = pd.read_csv(file_path_bufale_maggio, skiprows=1)
df_sniffer_giugno = pd.read_csv(file_path_bufale_giugno, skiprows=1)

/tmp/ipykernel_1025/1272735806.py:2: DtypeWarning: Columns (1,2,3,4,6,7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sniffer_giugno = pd.read_csv(file_path_bufale_giugno, skiprows=1)

In [21]:
df_sniffer_maggio.head()

,2024-05-15 22:00:00.066998,1177.8,772.679,2121.7,3819.079,0.659,40.67,995.509,32.468,32.252
0,2024-05-15 22:00:00.567837,1192.0,783.569,2245.6,4042.100,0.717,40.676,995.494,32.467,32.252
1,2024-05-15 22:00:01.069377,1146.7,752.276,2609.2,4696.583,0.593,40.695,995.465,32.467,32.252
2,2024-05-15 22:00:01.570569,1173.0,769.530,3199.1,5758.409,1.177,40.701,995.435,32.468,32.252
3,2024-05-15 22:00:02.072336,1316.7,863.803,4258.9,7666.058,0.601,40.719,995.421,32.466,32.252
4,2024-05-15 22:00:02.573411,1573.0,1031.945,6236.0,11224.856,0.801,40.725,995.416,32.466,32.252

In [20]:
df_sniffer_giugno.tail()

,timestamp,CH4,CH4-mgm3,CO2,CO2-mgm3,FLOW,H-AIR,P,T-AIR,T-BOX
1336406,06/14/2024 12:16:41.782150,691.5,453.19,523.3,941.945,0.608,32.412,1005.09,33.635,33.531
1336407,06/14/2024 12:16:42.785144,676.8,444.005,510.0,916.385,1.119,32.412,1005.134,33.635,33.531
1336408,06/14/2024 12:16:43.787620,748.7,491.174,508.8,915.845,1.139,32.418,1005.127,33.634,33.531
1336409,06/14/2024 12:16:44.790575,796.0,522.205,518.0,932.405,0.850,32.424,1005.093,33.633,33.531
1336410,06/14/2024 12:16:45.791937,860.2,564.322,481.2,860.584,0.565,32.43,1005.088,33.634,33.531

In [2]:
path="/mnt/c/Users/isabe/OneDrive/Desktop/Lavoro/Tuscia/chiara/peaks_background/bufale_isa/"
os.chdir(path)

In [3]:
file_path_robot = './dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Luglio/Dati_robot/Mungiture_1-31_luglio.csv'
file_path_bufale = './dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Luglio/Dati_moologger/Amaseno Luglio 2024-07012024115100-07312024115100.csv'

In [ ]:
#test dati luglio agosto (impossibile senza dati robot)

In [ ]:
#gestire dati agosto, formato diverso

In [5]:
#file_path_bufale = "./dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Luglio/Dati_moologger/luglio_detrended.csv"

df_sniffer = pd.read_csv(file_path_bufale, usecols=['timestamp', 'CH4', 'CH4-mgm3', 'CO2', 'CO2-mgm3'], skiprows=1)
df_sniffer.head()

/tmp/ipykernel_484/981426994.py:3: DtypeWarning: Columns (1,2,3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sniffer = pd.read_csv(file_path_bufale, usecols=['timestamp', 'CH4', 'CH4-mgm3', 'CO2', 'CO2-mgm3'], skiprows=1)

                    timestamp    CH4 CH4-mgm3    CO2  CO2-mgm3
0  07/01/2024 09:51:00.024698  195.8  128.452  645.1  1161.186
1  07/01/2024 09:51:01.026654  185.2  121.498  627.0  1128.606
2  07/01/2024 09:51:02.029196  195.8  128.452  602.3  1084.145
3  07/01/2024 09:51:03.032440  188.8   123.86  605.6  1090.085
4  07/01/2024 09:51:04.035013  191.8  125.828  611.2  1100.166

In [6]:
df_sniffer['timestamp'] = pd.to_datetime(df_sniffer['timestamp'])
df_sniffer['date'] = [d.date() for d in df_sniffer['timestamp']]
df_sniffer['time'] = [d.time() for d in df_sniffer['timestamp']]

In [ ]:
df_sniffer.head()

In [ ]:
df_sniffer.shape

In [ ]:
type(df_sniffer['date'][1])

In [7]:
date_str = '2024-07-01'
start_date = datetime.strptime(date_str, '%Y-%m-%d').date()
type(start_date)
df_sniffer = df_sniffer[df_sniffer['date'] >= start_date]

In [ ]:
df_sniffer.tail()

In [8]:
# Caricamento dei dati dal file CSV del robot di mungitura
df_robot = pd.read_csv(file_path_robot, header=1, sep=";", usecols=["Ora inizio", "Numero animale",
                                "Azione", "Durata (mm:ss)",
                                "Produzione (kg)", "Numero mungitura"])
df_robot['ID_animal'] = df_robot['Numero animale']
df_robot = df_robot.drop(columns = ['Numero animale'])

In [9]:
df_robot.head()

,Ora inizio,Azione,Durata (mm:ss),Produzione (kg),Numero mungitura,ID_animal
0,01/07/2024 00:13,Mungitura,05:00,"3,42",1.0,1687
1,01/07/2024 00:18,Mungitura,09:32,"1,20",1.0,5983
2,01/07/2024 00:30,Mungitura,05:13,"2,32",1.0,245572
3,01/07/2024 00:38,Rifiutata,00:00,NaN,NaN,245584
4,01/07/2024 00:38,Mungitura,07:48,"5,51",1.0,233727

In [ ]:
df_sniffer.tail()

In [10]:
# Filtraggio dei record con "Status" uguale a "Avvenuto con successo"
df_robot = df_robot[df_robot['Azione'] == 'Mungitura']

# Conversione e arrotondamento della colonna 'timestamp' al secondo più vicino nel DataFrame del Mologger
df_sniffer['timestamp'] = pd.to_datetime(df_sniffer['timestamp'], errors='coerce')

In [ ]:
type(df_robot['Durata (mm:ss)'][1])

In [11]:
df_robot['Milking_duration'] = df_robot['Durata (mm:ss)']
df_robot['Duration (hh:mm:ss)'] = '00:' + df_robot['Milking_duration']
df_robot['Duration (hh:mm:ss)'] = pd.to_timedelta(df_robot['Duration (hh:mm:ss)'])

In [12]:
df_robot['Milking_duration'] = df_robot['Milking_duration'].apply(lambda x: str(x))

In [ ]:
df_robot.head()

In [ ]:
df_sniffer.head()

In [13]:
#df_robot['Ora inizio'] = df_robot['Ora inizio'].apply(lambda x: x.strptime('%Y/%m/%d %H:%M:%S'))

df_robot['Ora inizio'] = pd.to_datetime(df_robot['Ora inizio'], format='%d/%m/%Y %H:%M')

In [14]:
df_robot_sorted = df_robot.sort_values('Ora inizio')

#df_robot_sorted=df_robot
df_robot_sorted['Ora inizio'] = pd.to_datetime(df_robot_sorted['Ora inizio'])

#associazione della durata di mungitura e ingresso bufala a misurazione sniffer con taglio del dato all'uscita dell'animale
df_robot_sorted['Milking_end'] = None
df_robot_sorted['Milking_end'] = df_robot_sorted['Ora inizio'] + df_robot_sorted['Duration (hh:mm:ss)']

In [ ]:
print(df_robot.shape)
print(df_sniffer.shape)
print(df_robot_sorted.shape)

In [15]:
#####
             
# Unione dei DataFrame df_robot e df_mologger basata sulla data con tolleranza di 1 minuto
# pulisci il timestamp per valori nan o assenti
df_sniffer.dropna(subset=['timestamp'], inplace=True)
df_sniffer.dropna(subset=['CH4'], inplace=True)

merged_df = pd.merge_asof(df_sniffer, df_robot_sorted, left_on='timestamp', right_on='Ora inizio')

merged_df=merged_df[merged_df['timestamp'] < merged_df['Milking_end']]

na_count = merged_df['CH4'].value_counts().get('N.A.', 0)
print("Count of 'N.A.' in the column CH4:", na_count)

Count of 'N.A.' in the column CH4: 0

In [16]:
merged_df.head()

,timestamp,CH4,CH4-mgm3,CO2,CO2-mgm3,date,time,Ora inizio,Azione,Durata (mm:ss),Produzione (kg),Numero mungitura,ID_animal,Milking_duration,Duration (hh:mm:ss),Milking_end
180,2024-07-01 09:54:00.472160,191.9,125.893,628.9,1131.126,2024-07-01,09:54:00.472160,2024-07-01 09:54:00,Mungitura,09:27,"1,44",2.0,5983,09:27,0 days 00:09:27,2024-07-01 10:03:27
181,2024-07-01 09:54:01.474686,182.0,119.399,602.2,1083.965,2024-07-01,09:54:01.474686,2024-07-01 09:54:00,Mungitura,09:27,"1,44",2.0,5983,09:27,0 days 00:09:27,2024-07-01 10:03:27
182,2024-07-01 09:54:02.476053,221.2,145.115,562.5,1012.505,2024-07-01,09:54:02.476053,2024-07-01 09:54:00,Mungitura,09:27,"1,44",2.0,5983,09:27,0 days 00:09:27,2024-07-01 10:03:27
183,2024-07-01 09:54:03.478415,218.4,143.278,574.1,1033.385,2024-07-01,09:54:03.478415,2024-07-01 09:54:00,Mungitura,09:27,"1,44",2.0,5983,09:27,0 days 00:09:27,2024-07-01 10:03:27
184,2024-07-01 09:54:04.481498,124.1,81.414,592.7,1066.325,2024-07-01,09:54:04.481498,2024-07-01 09:54:00,Mungitura,09:27,"1,44",2.0,5983,09:27,0 days 00:09:27,2024-07-01 10:03:27

In [17]:

#print("Data types of all columns:")
#print(merged_df.dtypes)

merged_df['CH4'] = pd.to_numeric(merged_df['CH4'], errors='coerce')

merged_df.replace(',', '.', regex=True, inplace=True)
merged_df.replace(':', '.', regex=True, inplace=True)
merged_df['Milking_duration'] = pd.to_numeric(merged_df['Milking_duration'], errors='coerce')
merged_df['Produzione (kg)'] = pd.to_numeric(merged_df['Produzione (kg)'], errors='coerce')

#print("Data types of all columns:")
#print(merged_df.dtypes)

#DO NOT perform if data are DETRENDED
#merged_df=merged_df[merged_df['CH4'] > 0]

#merged_df=merged_df[merged_df['CH4'] < 5000]

#output_file = './dati_bufale/merged_buffalo_sniffer_AMS.csv'
#merged_df.to_csv(output_file, index=False)

In [19]:
print(df_sniffer.shape)
print(merged_df.head())
print(merged_df.shape)

(1886873, 7)
                     timestamp    CH4 CH4-mgm3    CO2  CO2-mgm3        date  \
180 2024-07-01 09:54:00.472160  191.9  125.893  628.9  1131.126  2024-07-01
181 2024-07-01 09:54:01.474686  182.0  119.399  602.2  1083.965  2024-07-01
182 2024-07-01 09:54:02.476053  221.2  145.115  562.5  1012.505  2024-07-01
183 2024-07-01 09:54:03.478415  218.4  143.278  574.1  1033.385  2024-07-01
184 2024-07-01 09:54:04.481498  124.1   81.414  592.7  1066.325  2024-07-01

                time          Ora inizio     Azione Durata (mm:ss)  \
180  09:54:00.472160 2024-07-01 09:54:00  Mungitura          09.27
181  09:54:01.474686 2024-07-01 09:54:00  Mungitura          09.27
182  09:54:02.476053 2024-07-01 09:54:00  Mungitura          09.27
183  09:54:03.478415 2024-07-01 09:54:00  Mungitura          09.27
184  09:54:04.481498 2024-07-01 09:54:00  Mungitura          09.27

     Produzione (kg)  Numero mungitura  ID_animal  Milking_duration  \
180             1.44               2.0       5983              9.27
181             1.44               2.0       5983              9.27
182             1.44               2.0       5983              9.27
183             1.44               2.0       5983              9.27
184             1.44               2.0       5983              9.27

    Duration (hh:mm:ss)         Milking_end
180     0 days 00:09:27 2024-07-01 10:03:27
181     0 days 00:09:27 2024-07-01 10:03:27
182     0 days 00:09:27 2024-07-01 10:03:27
183     0 days 00:09:27 2024-07-01 10:03:27
184     0 days 00:09:27 2024-07-01 10:03:27
(890834, 16)

In [18]:
###CONTA MUNGITURE PER PERIODO
# Initialize 'Milking_number' column
merged_df['Milking_number'] = 0

# Initialize variables
milking_count = 0
previous_id = None

# Iterate through the DataFrame
for index, row in merged_df.iterrows():
    current_id = row['ID_animal']
   
    if current_id != previous_id:
        milking_count += 1
   
    # Update the 'Milking_number' column
    merged_df.at[index, 'Milking_number'] = milking_count
   
    # Update previous_id for the next iteration
    previous_id = current_id
    

output_file = './dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Luglio/protocollo_2/ch4_merged_sniffer_AMS.csv'
merged_df.to_csv(output_file, index=False)

In [ ]:
merged_df[1860:1870]

In [19]:
merged_df.tail(10)

,timestamp,CH4,CH4-mgm3,CO2,CO2-mgm3,date,time,Ora inizio,Azione,Durata (mm:ss),Produzione (kg),Numero mungitura,ID_animal,Milking_duration,Duration (hh:mm:ss),Milking_end,Milking_number
1886717,2024-07-23 12:42:26.860076,-98.5,-64.62,1981.5,3566.718,2024-07-23,12:42:26.860076,2024-07-23 12:38:00,Mungitura,04.33,3.07,2.0,233733,4.33,0 days 00:04:33,2024-07-23 12:42:33,1740
1886718,2024-07-23 12:42:27.861799,-9.6,-6.298,1830.2,3285.376,2024-07-23,12:42:27.861799,2024-07-23 12:38:00,Mungitura,04.33,3.07,2.0,233733,4.33,0 days 00:04:33,2024-07-23 12:42:33,1740
1886719,2024-07-23 12:42:28.864713,-5.5,-3.608,1681.1,3025.995,2024-07-23,12:42:28.864713,2024-07-23 12:38:00,Mungitura,04.33,3.07,2.0,233733,4.33,0 days 00:04:33,2024-07-23 12:42:33,1740
1886720,2024-07-23 12:42:29.867926,-24.6,-16.138,1518.4,2733.134,2024-07-23,12:42:29.867926,2024-07-23 12:38:00,Mungitura,04.33,3.07,2.0,233733,4.33,0 days 00:04:33,2024-07-23 12:42:33,1740
1886721,2024-07-23 12:42:30.871007,-49.6,-32.539,1322.2,2368.992,2024-07-23,12:42:30.871007,2024-07-23 12:38:00,Mungitura,04.33,3.07,2.0,233733,4.33,0 days 00:04:33,2024-07-23 12:42:33,1740
1886722,2024-07-23 12:42:31.873548,-72.7,-47.694,1117.6,2011.69,2024-07-23,12:42:31.873548,2024-07-23 12:38:00,Mungitura,04.33,3.07,2.0,233733,4.33,0 days 00:04:33,2024-07-23 12:42:33,1740
1886723,2024-07-23 12:42:32.875246,-91.2,-59.83,969.8,1745.649,2024-07-23,12:42:32.875246,2024-07-23 12:38:00,Mungitura,04.33,3.07,2.0,233733,4.33,0 days 00:04:33,2024-07-23 12:42:33,1740
1886870,2024-07-23 12:45:00.238828,-120.7,-79.184,729.3,1312.747,2024-07-23,12:45:00.238828,2024-07-23 12:45:00,Mungitura,06.08,3.73,2.0,245591,6.08,0 days 00:06:08,2024-07-23 12:51:08,1741
1886871,2024-07-23 12:45:01.241485,-124.0,-81.348,755.8,1360.447,2024-07-23,12:45:01.241485,2024-07-23 12:45:00,Mungitura,06.08,3.73,2.0,245591,6.08,0 days 00:06:08,2024-07-23 12:51:08,1741
1886872,2024-07-23 12:45:02.244261,-125.4,-82.267,729.2,1312.567,2024-07-23,12:45:02.244261,2024-07-23 12:45:00,Mungitura,06.08,3.73,2.0,245591,6.08,0 days 00:06:08,2024-07-23 12:51:08,1741