In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
import os

In [2]:
path="/mnt/c/Users/isabe/OneDrive/Desktop/Lavoro/Tuscia/chiara/peaks_background/bufale_isa/"
os.chdir(path)

In [3]:
#Lettura file dati mergiati ch4-bufale e robot, selezionando solo colonne che ci servono per questo momento.

mandria_path = './dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Luglio/protocollo_2/ch4_cutted_milkings.csv'
mandria = pd.read_csv(mandria_path, usecols = ['CH4', 'ID_animal', 'Milking_number', 'Produzione (kg)'])

mandria['ID_animal'] = mandria['ID_animal'].apply(lambda x: int(x))
mandria['Milking_number'] = mandria['Milking_number'].apply(lambda x: int(x))

animals = list(set(mandria['ID_animal']))
mungiture = list(set(mandria['Milking_number']))


print(len(animals))
print(len(mungiture))

36
1531

In [4]:
mandria.head()

     CH4  Produzione (kg)  ID_animal  Milking_number
0  102.1             1.44       5983               1
1   92.2             1.44       5983               1
2  131.4             1.44       5983               1
3  128.6             1.44       5983               1
4   34.3             1.44       5983               1

In [ ]:
#mandria_dropped = mandria
#mandria_dropped = pd.DataFrame(mandria[['CH4', 'Milking_number']])

In [ ]:
#mandria_dropped.head()

In [5]:
# Group by 'Milking_number' and calculate the mean of 'Methane'
average_methane_per_milking = mandria.groupby('Milking_number').mean().reset_index()

average_methane_per_milking.head()

#METANO MEDIO EMESSO PER MUNGITURA
mean_ch4_per_milking = average_methane_per_milking['CH4'].mean()

In [ ]:
#mandria_animal = mandria
#mandria_animal = pd.DataFrame(mandria[['CH4', 'Milking_number', 'ID_animal']])

In [ ]:
#mandria_animal.head()

In [6]:
# Group by 'Animal_ID' and count the unique 'Milking_number'
milking_count_per_animal = mandria.groupby('ID_animal')['Milking_number'].nunique().reset_index()

# Step 2: Group by 'Animal_ID' to calculate the average and standard deviation of the means
mean_and_std = average_methane_per_milking.groupby('ID_animal').agg({
    'CH4': ['mean', 'std'],
    'Produzione (kg)': 'mean'}).reset_index()

# Flatten the MultiIndex columns resulting from the aggregation
mean_and_std.columns = ['ID_animal', 'CH4_mean', 'CH4_std', 'avg_produzione']

In [7]:

# Salva il DataFrame combinato in un nuovo file CSV.
output_file = './dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Luglio/protocollo_2/mean_ch4_per_animal.xlsx'
mean_and_std.to_excel(output_file, index=False)


output_file_2 = './dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Luglio/protocollo_2/mean_ch4_per_milking.xlsx'
average_methane_per_milking.to_excel(output_file_2, index=False)
print("File CSV combinato creato con successo.")

File CSV combinato creato con successo.

In [8]:
mean_and_std.head()

   ID_animal    CH4_mean    CH4_std  avg_produzione
0     1007.0  102.228839  61.196777        1.697407
1     1646.0  126.311906  99.012592        1.976111
2     1687.0   90.329802  93.642767        4.094222
3     2857.0   90.096456  67.391091        2.034375
4     3098.0  103.970930  86.377929        6.567708

In [9]:
average_methane_per_milking.tail()

      Milking_number         CH4  Produzione (kg)  ID_animal
1526            1727    8.166667             2.41   234554.0
1527            1732  117.253673             4.56     5968.0
1528            1733  173.626053             3.63     4724.0
1529            1734  158.335455             3.43   242859.0
1530            1740  139.599231             3.07   233733.0